---
type: cnct
uniqueId: pipeline-jenkins
displayName: JenkinsCI pipeline
description: Pipeline Jenkins Helm chart and docker files
baseUrl: github.org
org: samsung-cnct
repo: pipeline-jenkins
keepDays: 10
credentials: github-access