---
type: standard
uniqueId: pipeline-jobs
displayName: Jenkins jobs pipeline
description: Job configuration repository
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: pipeline-jobs
keepDays: 10
credentials: github-access