---
type: standard
uniqueId: pipeline-jobs
displayName: Jenkins jobs pipeline
description: Job configuration repository
baseUrl: github.org
org: samsung-cnct
repo: pipeline-jobs
keepDays: 10
concurrent: true
credentials: github-access