---
type: cnct
uniqueId: pipeline-chart-eventrouter
displayName: Chart for eventrouter
description: A simple introspective kubernetes service that forwards events to a specified sink.
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: chart-eventrouter
keepDays: 10
credentials: github-access
