---
type: cnct
uniqueId: pipeline-container-eventrouter
displayName: Cluster-controller pipeline
description: A simple introspective kubernetes service that forwards events to a specified sink.
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: container-eventrouter
keepDays: 10
credentials: github-access
